name: olyChat
main: com.olympuspvp.chat.olyChat
version: 1.1.2
author: CalDaBeast
description: Chat handling

commands:
    cSet:
        description: set ChatItems in olyChat
    colors:
        description: gives the user a list of Minecraft-enabed colors
    who:
        description: gives a list of online players